### PR TITLE
Some improvements here and there ver2

### PR DESCRIPTION
**Pull request by bokic**

### CODE REVIEW

**Review by dridk — APPROVED** [review]

**Comment by dridk** [comment]
@bokic I fixed your code. There was a crash when reading compress file. e90c1a7110083223a7d2960b22717457995f0f86

'rawFile' is the compressed (*.fastq.gz) file or plain text file (*.fastq) . 
'file' is the uncompress file or plain text file (*.fastq) . 

To compute percent progression, we need to get the cursor position from the rawFile, not the KCompressFile. because I cannot have the total size of the KCompressfile.

**Comment by dridk** [comment]
and thx for your pull request. If you plan to do more, please do it on devel branch.

**Comment by bokic** [comment]
Guys, could you tell me where I could find some data files(I guess .fastq.gz or .fastq) so I can do some performance tests?

thanks..

**Comment by dridk** [comment]
You can find fastq file from 1000genomes project. There is  a data portal : http://www.internationalgenome.org/data-portal/sample

Actually we open : 
- fastq file 
- fastq.gz file 
- fastq.xz file 
- fastq.bz2 file

**Pull request merged**
